### ISSUE TITLE
Projektor not finding the kover xml report in the latest version of kover

### ISSUE THREAD

**Issue by togise** [craigatk/projektor#1016]
The latest kover and projector are not compatible because projector is looking [xmlReportFile on the koverXmlReportTask](https://github.com/craigatk/projektor/blob/06c45340afd64cda641fae4606a25d4bd24e1479/publishers/gradle-plugin/src/main/groovy/projektor/plugin/coverage/CodeCoverageTaskCollector.groovy#L56), while kover removed the xmlReportFile from property since [version 0.6.0](https://github.com/Kotlin/kotlinx-kover/blob/1d75e052ac079bd6a93234c754ee5d35a8dde885/docs/migration-to-0.6.0.md#property-xmlreportfile-was-removed).

I tested it using the sample project in this [repo](https://github.com/craigatk/projektor/tree/main/example-data/kover-gradle) and got the same result.

**Comment by craigatk** [comment]
@togise thanks for reporting this issue! 😄 

I have a fix for it and released a new version of the Projektor Gradle plugin `8.4.0` with the fix.
