### ISSUE TITLE
Error parsing test results, string length exceeds max limits

### ISSUE THREAD

**Issue by hobbs131** [craigatk/projektor#1149]
@craigatk Hello!

I've seen this error below for the past few months on our reports.

![Screenshot 2023-10-19 at 11 23 42 AM](https://github.com/craigatk/projektor/assets/60115853/82242ea7-3fc2-46cd-8018-86dbbd400cde)

It appears to be related to the [upgrade of Jackson](https://github.com/craigatk/projektor/pull/1018/files#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R14-R15:~:text=jacksonDatabindVersion%3D2.15.2,jacksonVersion%3D2.15.2) to 2.5.X, where a data size constraint was introduced to prevent malicious input — see [this comment](https://github.com/FasterXML/jackson-core/issues/1001#issuecomment-1527216221) for more detail.

Happy to help if this is something you'd like to address 😄

**Comment by craigatk** [comment]
@hobbs131 thanks so much for this report! :)

**Comment by craigatk** [comment]
Created a new server release v4.32.0 that increases the max payload size 2.5x over the default.

If you continue to run into issues with the payload size, please let me know and I can revisit it. Thanks!

**Comment by hobbs131** [comment]
> Created a new server release v4.32.0 that increases the max payload size 2.5x over the default.
> 
> If you continue to run into issues with the payload size, please let me know and I can revisit it. Thanks!

Really appreciate the fast response! Just ran tests — we're still seeing this error with the payload size increase.

**Comment by craigatk** [comment]
Argh, sorry you're still seeing the issue!

I'll update the server to make the max payload size configurable so you can hopefully find a value that works for your needs :)

**Comment by hobbs131** [comment]
> Argh, sorry you're still seeing the issue!
> 
> I'll update the server to make the max payload size configurable so you can hopefully find a value that works for your needs :)

No worries and thank you!

One thing to note: after switching to the new release, several users saw UI issues such as below. This was able to be resolved by a hard refresh, but we reverted in the meantime to avoid this confusion.

Hopefully making the payload size configurable with the old default value of `20_000_000` solves this 😄 

![Screenshot 2023-10-28 at 8 30 35 AM](https://github.com/craigatk/projektor/assets/60115853/d505f681-d887-466d-b0ea-406565a2a483)

**Comment by craigatk** [comment]
In the next release, there will be a server environment variable `MAX_PAYLOAD_SIZE` where you can control the max payload size the server will accept. The default is `50000000` (50 million length)

Thanks for the heads up about the UI weirdness - I'll investigate!

**Comment by craigatk** [comment]
Newly-released server version `4.33.0` has the configurable max payload size and a fix for the styling regressions. Thanks again for reporting these issues!
