### ISSUE TITLE
It would be nice to add the filename for failed tests

### ISSUE THREAD

**Issue by ackmanx** [craigatk/projektor#1190]
Projektor version: Unknown, this is managed by another team within my company

I've always been curious how the display of test names works and if there's an easier way to find which tests are failing. It would be helpful if the file name was reported.

Is there a trick to finding out? I usually try and find a substring of the below example and search our codebase for it but it's very very tricky oftentimes.

Example:
> section management.should have two sections two section component type section management should have two sections

`section management` is a 2nd level _describe_
`should have two sections` is the test name
`two section component type` is the 1st level _describe_

So in essence, what Projektor is reporting is this template:
`{2nd-level describe}.{test name} {top level describe} {2nd-level describe} {test name}`

![projektor](https://github.com/craigatk/projektor/assets/7490057/b960bf8e-d230-471b-a463-15e5a82630dc)

**Comment by craigatk** [comment]
Hello, thanks for the detailed report and for including a screenshot!

From looking at the screenshot, this looks like a Cypress test? For Cypress tests, Projektor is constrained by the output format from Cypress's JUnit reporter for how the test name is represented. But I hear you that having the test file name would be nice. Projektor has the file name for certain types of tests, I'll see if I can get the file name added to the UI.

**Comment by craigatk** [comment]
Added the test file name to the failed tests view and released a new version of the Projektor server with the changes: https://github.com/craigatk/projektor/releases/tag/v4.33.2

![Screenshot 2024-03-23 at 9 49 09 AM](https://github.com/craigatk/projektor/assets/252174/f5cb3125-20c4-45cb-b408-8436da5bf9e2)

Example test report: https://projektorlive.herokuapp.com/tests/MFOST3PJVUDF/failed

**Comment by ackmanx** [comment]
This is fantastic. Nice!
