### ISSUE TITLE
API for Org/Repo details with Test Report/Coverage 

### ISSUE THREAD

**Issue by aritras25** [craigatk/projektor#1207]
It would be great if there is an API, through which we can query the postgres to get the Repo details and respective Report details.

**Comment by craigatk** [comment]
Sure, there aren't docs currently for it but one option could be to use the API routes that the Projektor UI calls and pull data from those.

Test reports aren't stored at the code repo level currently, but you could theoretically get coverage data for specific repos from API endpoints such as https://github.com/craigatk/projektor/blob/main/server/server-app/src/main/kotlin/projektor/route/RepositoryCoverageRoutes.kt#L26

**Comment by craigatk** [comment]
Also, are there specific types of reports you're looking to generate with test result or code coverage data from Projektor? Is it something we could potentially add to Projektor itself?

**Comment by aritras25** [comment]
I had already tried using the API endpoint which UI exposes through Postman and got html response, not the list of repo and coverage details. 
<img width="1299" alt="Screenshot 2024-03-24 at 4 33 33 PM" src="https://github.com/craigatk/projektor/assets/37728499/aaaa7fd7-c2a3-474b-ad96-735bd36f42ca">


What I am looking for : 
1) I am seeking to develop a dashboard that incorporates organizational tags (Org Tag), allowing users to click on an organization and view a list of all associated repositories, along with their respective coverage metrics.
2) Furthermore, I aim to introduce an additional layer of hierarchy between organizations and repositories, such as products. The envisioned structure would resemble: Department --> Organization --> Product --> Repository --> Coverage.
3) Given the current framework, if the API functions, as intended, I have the capability to internally map departments to organizations. Additionally, I can manage the hierarchy from organization to product to repository effectively.

**Comment by craigatk** [comment]
Thanks for sharing that context!

For the code coverage for a given organization, the current org-level coverage page might do the trick (accessible from the "Organization" side menu link): https://projektorlive.herokuapp.com/organization/craigatk

For the additional hierarchy options for reporting, that definitely makes sense. I have some ideas on how that could potentially be implemented in Projektor, but it would be a decent lift so just to set expectations I wouldn't rely on it being available right away.

In the meantime, would the API that powers the org-level coverage page potentially get you the necessary data to build the report on your end? https://github.com/craigatk/projektor/blob/main/server/server-app/src/main/kotlin/projektor/route/OrganizationRoutes.kt#L12

**Comment by craigatk** [comment]
Thanks again for the feedback about adding an API to get coverage data!

I added initial API endpoints meant for external consumption (vs reusing the endpoints the UI calls) and documented them here: https://projektor.dev/docs/api/

**Comment by aritras25** [comment]
Hello @craigatk Sorry was out for couple of days, couldn't check the solution.
Thanks a lot for sharing the initial api on request. I will implement the same and get back to you with feedback!!

**Comment by craigatk** [comment]
I also added endpoints to fetch the latest test run summaries for a repo and flaky test information:

* Test run summaries: https://projektor.dev/docs/api/#test-runs
* Flaky test runs: https://projektor.dev/docs/api/#flaky-tests

**Comment by aritras25** [comment]
Hello @craigatk , this is great !! Integrated these ones and worked flawlessly, fulfilled the purpose as well.. Thanks Much !!

**Comment by aritras25** [comment]
I will close this issue in a week's time

**Comment by craigatk** [comment]
@aritras25 excellent, I'm glad those API endpoints are working for you! :)

**Comment by craigatk** [comment]
Closing this issue for now, please feel free to open additional issues if there are other API endpoints that would be helpful :)
