### ISSUE TITLE
Maven missing v4.0.2

### ISSUE THREAD

**Issue by ahatzz11** [craigatk/projektor#32]
I am trying to use the `ProjektorPublishPlugin` so I can apply projektor in my own plugin, I add projektor to my classpath:

```groovy
dependencies {
    compile "org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion"
    compile 'dev.projektor.publish:dev.projektor.publish.gradle.plugin:4.0.1'
}
```

and I am able to use it in my plugin code:

```groovy
class MyPlugin implements Plugin<Project> {

    @Override
    void apply(Project project) {
        project.repositories {
            mavenLocal()
            maven { url 'https://plugins.gradle.org/m2/' }
        }

        project.plugins.apply(SpingBootPlugin)
        project.plugins.apply(ProjektorPublishPlugin)

        project.projektor {
            serverUrl = "https://myserver"
        }
    }
}
```

However, I noticed that the [maven repo](https://mvnrepository.com/artifact/dev.projektor.publish/dev.projektor.publish.gradle.plugin) seems to not have the latest version available to use in this way

I've also submitted #33 to add some more documentation around using the plugin in this way.

**Comment by craigatk** [comment]
Thanks for including all the great detail in this issue!

The plugin is published to the Gradle plugin portal, but I'm not sure where that other Maven repo is getting its artifacts - maybe it's mirroring the Gradle plugin repo but is a bit delayed (v4.0.2 was published just last Thursday).

Either way, adding the Gradle plugin portal as a repo (https://plugins.gradle.org/m2/) should let you pull in the plugin as a dependency.

I tried this sample build script locally and it pulled in the dependency for me:

```
plugins {
    id 'groovy'
}

repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
}

dependencies {
    implementation 'dev.projektor.publish:dev.projektor.publish.gradle.plugin:4.0.2'
}
```

**Comment by ahatzz11** [comment]
That worked great! I guess I never realized that gradle had it's own portal for plugins.

Interestingly enough, it looks like maven has `4.0.2` now - https://mvnrepository.com/artifact/dev.projektor.publish/dev.projektor.publish.gradle.plugin/4.0.2 - There must be some sort of mirroring going on somewhere. 

Thanks for the help! I'll close this out.
