### ISSUE TITLE
Ingesting Cobertura coverage XML?

### ISSUE THREAD

**Issue by colindean** [craigatk/projektor#360]
I've got a Python project wherein I'm using [Coverage.py](https://coverage.readthedocs.io) via [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/) when I run pytest. Coverage.py produces Cobertura XML, but not Jacoco XML.

An external conversion step is acceptable in my workflow. I've [searched a bit](https://duckduckgo.com/?q=jacoco+cobertura+convert) and really only found [cover2cover](https://github.com/rix0rrr/cover2cover), which converts Jacoco to Cobertura, but not vice-versa.

I'd love to this work somehow, whether that's Cobertura XML ingest support in Projektor, [Jacoco XML output implemented in Coverage.py](https://github.com/nedbat/coveragepy/issues/534), or some tool that complements cover2cover in reverse.

**Comment by craigatk** [comment]
Sounds good, the Cobertura report format is an output option for this and other coverage tools I've seen so I think it's worth adding support for it in Projektor.

That'd be awesome if you're up for trying to add Cobertura support in Projektor! If it helps, I can give a rough outline of the steps I'd take:

1. Create a new Gradle subproject under `server/parsing` that houses the Jackson XML model objects for that represent the Cobertura XML format. Similar to the `jacoco-xml-parser` and `jest-xml-parser` subproject in there.
2. Add a new `CoberturaCoverageReportParser` class in the `server/parsing/coverage-parser` that converts the Cobertura model from step 1 into the format-agnostic coverage data format that Projektor uses internally. Again there are a couple existing examples `JacocoCoverageReportParser` and `CloverCoverageReportParser`
3. Update the logic in `CoverageParser` in `server/parsing/coverage-parser` to identify when it's a Cobertura report file and delegate to the new coverage parser.

Or I'm happy to add the Cobertura support myself if that's a route you'd rather go, just let me know. Thanks!

**Comment by colindean** [comment]
If it is something that you can do with relative ease and speed, please don't wait for me! It could be weeks until I get around to it, If ever.

**Comment by craigatk** [comment]
Support for Cobertura test coverage added in Projektor server `4.15.0`
