### ISSUE TITLE
Gradle plugin uses deprecated features to be removed in Gradle 8.0

### ISSUE THREAD

**Issue by ErikKringen** [craigatk/projektor#434]
When adding the gradle plugin to a gradle 7.2, the following warnings are issues.

> The Report.enabled property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the required property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:enabled for more details.
> The Report.destination property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the outputLocation property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:destination for more details.

I can trace these back to this plugin, and are not present if the plugin is removed.

**Comment by craigatk** [comment]
Thanks for reporting this issue! I'll look into removing those deprecated usages.

**Comment by craigatk** [comment]
Released Projektor Gradle plugin `7.6.0` that should avoid using these deprecated properties.
