### ISSUE TITLE
Feature request: Be able to highlight the collapsable section titles on the tests page

### ISSUE THREAD

**Issue by rgatti** [craigatk/projektor#449]
On the Tests page the failed tests are listed in collapsable sections. When I try to highlight the title (class name) for one of these sections in Safari it simply toggles the section open or closed.

Currently, the only way I know to get the failed class that I can copy is by expanding the failed test, then going to Failure Details > Summary.

**Comment by craigatk** [comment]
Thanks for reporting this! I'll look into ways to make this more user-friendly.

**Comment by craigatk** [comment]
Fixed selection of the failed test class name in Safari in https://github.com/craigatk/projektor/pull/461

Triggering the expand/collapse when selecting the text name is also annoying across all browsers, so I narrowed-down the expand/collapse to just the arrow icon and not on the text itself.
