### ISSUE TITLE
NPE thrown if Kover report not found

### ISSUE THREAD

**Issue by arudge** [craigatk/projektor#689]
If the kover report is not yet present, an NPE is thrown causing the projektor publish to fail.
```
* What went wrong:
java.io.FileNotFoundException: /build/reports/kover/report.xml (No such file or directory)
> /build/reports/kover/report.xml (No such file or directory)
```

**Comment by arudge** [comment]
It doesn't appear that I can assign this to myself, but I'm working on a fix currently.

**Comment by craigatk** [comment]
Thanks for tackling this one! I can assign the ticket to you.

**Comment by craigatk** [comment]
Gradle plugin release `8.0.2` has a potential fix for this issue. When you get a chance, please give it a try and let me know if the fix is working for you.

**Comment by arudge** [comment]
Thanks for releasing the new gradle plugin version @craigatk .
